version: '3.4'

services:
  webfe:
    build: .
    command: python app.py
    ports:
      - target: 5000
        published: 5000
    networks:
      - frontend-net
      - backend-net
    volumes:
      - type: volume
        source: counter-vol
        target: /code


  redis:
    image: "redis:alpine"
    networks:
      - backend-net

networks:
  frontend-net:
  backend-net:
    internal: true
    

volumes:
  counter-vol: